### ISSUE TITLE
Dutch languages pack doest work

### ISSUE THREAD

**Issue by RolandGort** [babbelaar/vscode-dutch-language#4]
Can't install 'babbelaar.babbelaar-vscode-language-pack-nl' extension because it is not compatible with the current version of Visual Studio Code (version 1.72.2).

**Comment by usadson** [comment]
Hey Roland, I'm sorry to hear things aren't working out-of-the-box. I've updated the extension to remove the specific requirement, as my VS Code version is older than the version you've installed. 

If you could try to update [the extension](https://marketplace.visualstudio.com/items?itemName=babbelaar.babbelaar-vscode-language-pack-nl), I hope this solves the problem for you. ☺️

(I don't know how to install an older version than currently installed, so I hope this works)

**Comment by RolandGort** [comment]
Hola, Thank you for your update and help to fix the problem. 
I did install the dutch language and it works! :)
Thanks for the hard work!

Atentamente, Met vriendelijke groet, With kind regards,

Roland en Chantal Gort
***@***.***

**Comment by usadson** [comment]
Glad to hear it worked out! 🤩
